### ISSUE TITLE
MVP TODO

### ISSUE THREAD

**Issue by collingreen** [collingreen/teaching-python#8]
- [ ] clarify the goals
- [ ] clear instructions for windows and mac for how to get started
  - maybe jupyter helps with this
- [ ] figure out a format that works for people and is scalable
